import * as fs from 'node:fs';
import * as path from 'node:path';
import type {
  FlightPlan,
  TechStackDetection,
  ScenarioMatch,
} from './types.js';

export interface GeneratePlanOptions {
  projectDir: string;
  assessmentOutputPath: string;
  installedPlans: Array<{
    scenarioName: string;
    plan: FlightPlan;
    installedPath: string;
  }>;
  detections: TechStackDetection[];
  matches: ScenarioMatch[];
}

/**
 * Generate an integrated modernization plan document that makes flight plans
 * first-class citizens. The plan includes governance gates, orchestration steps,
 * skills by phase, and execution roadmap.
 *
 * @returns The absolute path to the generated plan file.
 */
export function generateModernizationPlan(options: GeneratePlanOptions): string {
  const {
    projectDir,
    assessmentOutputPath,
    installedPlans,
    detections,
    matches,
  } = options;

  const timestamp = new Date().toISOString().split('T')[0];
  const sections: string[] = [];

  // Header
  sections.push(`# Integrated Modernization Plan`);
  sections.push(`<!-- Generated by modernize assess --with-flightplans on ${timestamp} -->`);
  sections.push('');

  // Assessment Summary
  sections.push('## Assessment Summary');
  sections.push('');
  sections.push(`Assessment report location: \`${assessmentOutputPath}\``);
  sections.push('');

  // Detected Tech Stack
  sections.push('## Detected Technology Stack');
  sections.push('');
  if (detections.length > 0) {
    sections.push('| Property | Value | Evidence |');
    sections.push('|----------|-------|----------|');
    for (const d of detections) {
      const evidenceSummary = d.evidence
        .slice(0, 3)
        .map(e => `${e.file}: ${e.property}=${e.value}`)
        .join('; ');
      sections.push(`| Language | ${d.language} | ${evidenceSummary} |`);
      if (d.framework) {
        sections.push(`| Framework | ${d.framework} | |`);
      }
      if (d.frameworkVersion) {
        sections.push(`| Framework Version | ${d.frameworkVersion} | |`);
      }
      if (d.buildSystem) {
        sections.push(`| Build System | ${d.buildSystem} | |`);
      }
      if (d.runtimeVersion) {
        sections.push(`| Runtime Version | ${d.runtimeVersion} | |`);
      }
      sections.push(`| Repository Type | ${d.repositoryType} | |`);
    }
  } else {
    sections.push('No technology stack detected.');
  }
  sections.push('');

  // Installed Flight Plans summary table
  sections.push('## Installed Flight Plans');
  sections.push('');
  if (installedPlans.length > 0) {
    sections.push('| # | Scenario | Version | Confidence | Description |');
    sections.push('|---|----------|---------|------------|-------------|');
    for (let i = 0; i < installedPlans.length; i++) {
      const ip = installedPlans[i];
      const match = matches.find(m => m.scenario.name === ip.scenarioName);
      const confidence = match?.confidence?.toUpperCase() ?? 'N/A';
      const description = match?.scenario?.description ?? ip.plan.intent.split('\n')[0];
      sections.push(`| ${i + 1} | ${ip.scenarioName} | ${ip.plan.version} | ${confidence} | ${truncate(description, 80)} |`);
    }
  } else {
    sections.push('No flight plans installed.');
  }
  sections.push('');

  // Per-flight-plan detailed sections
  for (let i = 0; i < installedPlans.length; i++) {
    const ip = installedPlans[i];
    sections.push('---');
    sections.push('');
    sections.push(formatFlightPlanSection(i + 1, ip.scenarioName, ip.plan, ip.installedPath));
  }

  // Execution Roadmap (merged phases)
  sections.push('---');
  sections.push('');
  sections.push(buildExecutionRoadmap(installedPlans));

  // Quick Reference Commands
  sections.push('## Quick Reference Commands');
  sections.push('');
  sections.push('```bash');
  sections.push('modernize flightplan status                    # See installed plan + gate evaluation');
  sections.push('modernize flightplan gates                     # Evaluate all gates');
  sections.push('modernize flightplan gates --type entry        # Check entry gates only');
  sections.push('modernize flightplan run 00-assess             # Display Step 00 prompt');
  sections.push('modernize flightplan run 01-vision             # Display Step 01 prompt');
  sections.push('modernize flightplan run 06-implement          # Display implementation prompt');
  sections.push('modernize flightplan gates --type exit         # Verify exit gates pass');
  sections.push('```');
  sections.push('');

  // Write file
  const outputDir = path.join(path.resolve(projectDir), '.github', 'modernize');
  fs.mkdirSync(outputDir, { recursive: true });
  const outputPath = path.join(outputDir, 'modernization-plan.md');
  fs.writeFileSync(outputPath, sections.join('\n'), 'utf-8');

  return outputPath;
}

// ---------------------------------------------------------------------------
// Format a single flight plan section
// ---------------------------------------------------------------------------

function formatFlightPlanSection(
  index: number,
  scenarioName: string,
  plan: FlightPlan,
  installedPath: string,
): string {
  const lines: string[] = [];

  lines.push(`## Flight Plan ${index}: ${scenarioName} (v${plan.version})`);
  lines.push('');

  // Intent
  lines.push('### Intent');
  lines.push('');
  lines.push(plan.intent.trim());
  lines.push('');

  // Parameters
  const params = plan.parameters ?? {};
  if (Object.keys(params).length > 0) {
    lines.push('### Parameters');
    lines.push('');
    lines.push('| Parameter | Value |');
    lines.push('|-----------|-------|');
    for (const [key, value] of Object.entries(params)) {
      lines.push(`| ${key} | ${value} |`);
    }
    lines.push('');
  }

  // Skills by Phase
  if (plan.skills.length > 0) {
    lines.push('### Skills by Phase');
    lines.push('');
    const phases = groupByPhase(plan.skills);
    for (const [phase, skills] of Object.entries(phases)) {
      lines.push(`**${capitalize(phase)}:**`);
      for (const skill of skills) {
        const shared = skill.location === 'shared' ? ' [shared]' : '';
        lines.push(`- ${skill.id} (v${skill.version})${shared}`);
      }
      lines.push('');
    }
  }

  // Governance Gates
  lines.push('### Governance Gates');
  lines.push('');

  const gateCategories: Array<{ key: keyof typeof plan.gates; label: string }> = [
    { key: 'entry', label: 'Entry Gates (must pass before starting)' },
    { key: 'output_integrity', label: 'Output Integrity Gates' },
    { key: 'risk', label: 'Risk Gates' },
    { key: 'exit', label: 'Exit Gates (must pass for completion)' },
  ];

  for (const { key, label } of gateCategories) {
    const gates = plan.gates[key] ?? [];
    if (gates.length > 0) {
      lines.push(`#### ${label}`);
      for (const gate of gates) {
        lines.push(`- [ ] **${gate.name}**: ${gate.description}`);
        lines.push(`  - Condition: \`${gate.condition}\``);
      }
      lines.push('');
    }
  }

  // Required Artifacts
  if (plan.required_artifacts.length > 0) {
    lines.push('### Required Artifacts');
    lines.push('');
    for (const artifact of plan.required_artifacts) {
      lines.push(`- [ ] \`${artifact.name}\` - ${artifact.description}`);
    }
    lines.push('');
  }

  // Human Controls
  if (plan.human_controls.length > 0) {
    lines.push('### Human Controls (mandatory pause points)');
    lines.push('');
    for (const control of plan.human_controls) {
      lines.push(`- **${control.trigger}**: ${control.description}`);
    }
    lines.push('');
  }

  // Orchestration Steps
  lines.push('### Orchestration Steps');
  lines.push('');
  const steps = listOrchestrationSteps(installedPath);
  if (steps.length > 0) {
    lines.push('| Step | Name | Prompt File |');
    lines.push('|------|------|-------------|');
    for (const step of steps) {
      lines.push(`| ${step.step} | ${step.name} | ${step.file} |`);
    }
    lines.push('');
    lines.push(`Run: \`modernize flightplan run <step>\` to display each prompt.`);
  } else {
    lines.push('No orchestration prompts found.');
  }
  lines.push('');

  return lines.join('\n');
}

// ---------------------------------------------------------------------------
// Execution Roadmap
// ---------------------------------------------------------------------------

function buildExecutionRoadmap(
  plans: Array<{ scenarioName: string; plan: FlightPlan }>,
): string {
  const lines: string[] = [];
  lines.push('## Execution Roadmap');
  lines.push('');

  // Merge all skills across plans, grouped by phase
  const phaseOrder = ['discovery', 'migration', 'infrastructure', 'validation'];
  const phaseSkills = new Map<string, Array<{ scenario: string; skillId: string; version: string; shared: boolean }>>();

  for (const phase of phaseOrder) {
    phaseSkills.set(phase, []);
  }

  for (const p of plans) {
    for (const skill of p.plan.skills) {
      const phase = skill.phase.toLowerCase();
      if (!phaseSkills.has(phase)) {
        phaseSkills.set(phase, []);
      }
      phaseSkills.get(phase)!.push({
        scenario: p.scenarioName,
        skillId: skill.id,
        version: skill.version,
        shared: skill.location === 'shared',
      });
    }
  }

  let stepNum = 1;
  for (const phase of phaseOrder) {
    const skills = phaseSkills.get(phase) ?? [];
    if (skills.length === 0) continue;

    lines.push(`### Phase: ${capitalize(phase)}`);
    lines.push('');

    // Add orchestration step reference for this phase
    if (phase === 'discovery') {
      lines.push(`${stepNum}. Run \`modernize flightplan run 00-assess\` -- Assess the application`);
      stepNum++;
      lines.push(`${stepNum}. Run \`modernize flightplan run 01-vision\` -- Establish migration vision`);
      stepNum++;
    } else if (phase === 'migration') {
      lines.push(`${stepNum}. Run \`modernize flightplan run 02-roadmap\` -- Create migration roadmap`);
      stepNum++;
      lines.push(`${stepNum}. Run \`modernize flightplan run 03-progress\` -- Create progress tracker`);
      stepNum++;
      lines.push(`${stepNum}. Run \`modernize flightplan run 04-plan\` -- Queue work items`);
      stepNum++;
      lines.push(`${stepNum}. Run \`modernize flightplan run 05-spec\` -- Spec next work item`);
      stepNum++;
      lines.push(`${stepNum}. Run \`modernize flightplan run 06-implement\` -- Implement work item`);
      stepNum++;
    } else if (phase === 'validation') {
      lines.push(`${stepNum}. Run \`modernize flightplan run 07-iterate\` -- Feedback and iterate`);
      stepNum++;
    }

    lines.push('');
    lines.push('**Skills to execute:**');
    for (const s of skills) {
      const sharedTag = s.shared ? ' [shared]' : '';
      lines.push(`- [${s.scenario}] ${s.skillId} (v${s.version})${sharedTag}`);
    }
    lines.push('');
  }

  // Gate checkpoint
  lines.push('### Final Verification');
  lines.push('');
  lines.push('```bash');
  lines.push('# Verify all exit gates pass');
  lines.push('modernize flightplan gates --type exit');
  lines.push('```');
  lines.push('');

  return lines.join('\n');
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function listOrchestrationSteps(
  installedPath: string,
): Array<{ step: string; name: string; file: string }> {
  const promptsDir = path.join(installedPath, 'Prompts');
  if (!fs.existsSync(promptsDir)) return [];

  const stepNames: Record<string, string> = {
    '00': 'Assess the application',
    '01': 'Establish the migration vision',
    '02': 'Create the migration roadmap',
    '03': 'Create a progress tracker',
    '04': 'Queue work items',
    '05': 'Spec the next work item',
    '06': 'Implement the work item',
    '07': 'Feedback and iterate',
  };

  const steps: Array<{ step: string; name: string; file: string }> = [];

  try {
    const files = fs.readdirSync(promptsDir);
    for (const file of files) {
      if (file.endsWith('.prompt.md')) {
        const stepMatch = file.match(/^(\d{2})/);
        if (stepMatch) {
          const stepNum = stepMatch[1];
          steps.push({
            step: stepNum,
            name: stepNames[stepNum] ?? file,
            file: `Prompts/${file}`,
          });
        }
      }
    }
  } catch {
    // skip if unreadable
  }

  return steps.sort((a, b) => a.step.localeCompare(b.step));
}

function groupByPhase(
  skills: FlightPlan['skills'],
): Record<string, FlightPlan['skills']> {
  const grouped: Record<string, FlightPlan['skills']> = {};
  for (const skill of skills) {
    const phase = skill.phase ?? 'other';
    if (!grouped[phase]) grouped[phase] = [];
    grouped[phase].push(skill);
  }
  return grouped;
}

function capitalize(s: string): string {
  return s.charAt(0).toUpperCase() + s.slice(1);
}

function truncate(s: string, maxLen: number): string {
  if (s.length <= maxLen) return s;
  return s.slice(0, maxLen - 3) + '...';
}
